image:
    pattern:  /
    defaults: { _controller: "DWSlideShowBundle:Image:index" }

image_show:
    pattern:  /{id}/show
    defaults: { _controller: "DWSlideShowBundle:Image:show" }

image_new:
    pattern:  /new
    defaults: { _controller: "DWSlideShowBundle:Image:new" }

image_create:
    pattern:  /create
    defaults: { _controller: "DWSlideShowBundle:Image:create" }
    requirements: { _method: post }

image_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "DWSlideShowBundle:Image:edit" }

image_update:
    pattern:  /{id}/update
    defaults: { _controller: "DWSlideShowBundle:Image:update" }
    requirements: { _method: post }

image_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "DWSlideShowBundle:Image:delete" }
    requirements: { _method: post }
